#!/bin/bash

#nvim
alias vi='pass show -c chatgpt && nvim'
#Git aliases
alias gs='git status'
#Git combo which will ask for commit, otherwise do it all
alias gacp='git add . && git commit -e && if [ $? -eq 0 ]; then git push; fi'

#Chezmoi
alias ch='chezmoi'

#Tmux
# Define alias function
tmuxAttach() {
    if [ -z "$1" ]; then
        tmux attach
    else
        tmux attach -t "$1"
    fi
}


tmuxNewSession() {
    if [ -z "$1" ]; then
        tmux 
    else
        tmux new-session -s "$1"
    fi
}

# Create alias
alias tma='tmuxAttach'
alias tm='tmuxNewSession'
alias tml='tmux ls'
