#!/bin/bash

#linux commands
alias cl='clear'
alias cls='clear && ls'
alias ls='ls -a'

#aliases-file
alias va='nvim ~/.aliases'
alias sa='source ~/.aliases'

#nvim
# not using chatgpt atm
# alias v='pass show personal/chatgpt && nvim'
alias v='nvim'
alias vi='echo vi is old shit, just use v'

#Git aliases
alias gs='git status'
# Git combo which will ask for commit, otherwise do it all
# alias gacp='git add . && git commit -e && if [ $? -eq 0 ]; then git push; fi'

# Lazygit
alias lg='lazygit'

#Copypath
alias copa='copypath'

#Chezmoi
alias ch='chezmoi'
alias chan='chezmoi add -r ~/.config/nvim/ && chezmoi cd && git status'

#Tmux
# Define alias function
tmuxAttach() {
    if [ -z "$1" ]; then
        tmux attach
    else
        tmux attach -t "$1"
    fi
}


tmuxNewSession() {
    if [ -z "$1" ]; then
        tmux 
    else
        tmux new-session -s "$1"
    fi
}

# Create alias
alias tma='tmuxAttach'
alias tm='tmuxNewSession'
alias tml='tmux ls'

#cd directly to specicif directorys
alias tf='cd ~/af-projects/tajma-frontend/'
alias tb='cd ~/af-projects/tajma-backend/'
alias tc='cd ~/af-projects/tajma-config/argocd_ocp4/'
alias vc='cd ~/.config/nvim/'

#Node
alias ns='npm start'
alias node='ts-node'

#Open directory in vim
alias vcv=';vc ; v'
alias tfv='cd ~/af-projects/tajma-frontend &&; v'
alias tbv='cd ~/af-projects/tajma-backend &&; v'
alias tcv='cd ~/af-projects/tajma-config &&; v'
#vimwiki.
alias vwv='cd ~/vimwiki &&; v index.wiki'

#edit settings.json for windows terminal
alias vwts='cd /mnt/c/Users/hoaje/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState && v settings.json'

#xclip
alias xclip='xclip -sel clip'

#browser
alias edge='/mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe'
alias chrome='/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe'

#Running Tajma
alias tajba='cd ~/af-projects/tajma-backend && mvn spring-boot:run -Dspring-boot.run.arguments="--spring.profiles.active=dev"'
alias tajfro='cd ~/af-projects/tajma-frontend &&; ns' 
