#!/bin/bash

#linux commands
alias cl='clear'
alias cls='clear && ls'

#aliases-file
alias va='nvim ~/.aliases'
alias sa='source ~/.aliases'

#nvim
alias v='pass show chatgpt && nvim'
alias vi='echo vi is old shit, just use v'

#Git aliases
alias gs='git status'
#Git combo which will ask for commit, otherwise do it all
alias gacp='git add . && git commit -e && if [ $? -eq 0 ]; then git push; fi'

#Copypath
alias copa='copypath'

#Chezmoi
alias ch='chezmoi'
alias chan='chezmoi add -r ~/.config/nvim/ && chezmoi cd && git status'

#Tmux
# Define alias function
tmuxAttach() {
    if [ -z "$1" ]; then
        tmux attach
    else
        tmux attach -t "$1"
    fi
}


tmuxNewSession() {
    if [ -z "$1" ]; then
        tmux 
    else
        tmux new-session -s "$1"
    fi
}

# Create alias
alias tma='tmuxAttach'
alias tm='tmuxNewSession'
alias tml='tmux ls'

#cd directly to specicif directorys
alias tf='cd ~/af-projects/tajma-frontend/'
alias tb='cd ~/af-projects/tajma-backend/'
alias tc='cd ~/af-projects/tajma-config/argocd_ocp4/'
alias vc='cd ~/.config/nvim/'

#Node
alias node='ts-node'

#Open directory in vim
alias vvc='cd ~/.config/nvim/ &&; v'
alias vtf='cd ~/af-projects/tajma-frontend &&; v'
alias vtb='cd ~/af-projects/tajma-backend &&; v'
alias vtc='cd ~/af-projects/tajma-config &&; v'


